server:
  port: 9000

spring:
  session:
      store-type: redis
  datasource:
    url: jdbc:mariadb://localhost:3306/bookreview
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO

jwt:
  private-key: classpath:private.key
  public-key: classpath:public.pub