server:
  port: 9000

spring:
  session:
      store-type: redis
  datasource:
    url: jdbc:mariadb://localhost:3306/bookreview
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 1234
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5MB
  sql:
    init:
      mode: always
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO

jwt:
  private-key: classpath:private.key
  public-key: classpath:public.pub
